name: heartbit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_messaging: ^16.1.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Routing
  go_router: ^15.1.2
  
  # Utils
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.2
  intl: ^0.19.0
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  
  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  confetti: ^0.8.0
  flutter_card_swiper: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
